# DO NOT CHANGE -> WILL BREAK copier LOGIC
_commit: v0.9.0
_src_path: https://github.com/taranis-ai/bot_template
author_mail: benjamin.akhras@ait.ac.at
description: Sentiment analysis Bot for Taranis AI
init_git_repo: true
models: roberta, longformer
project_name: sentiment_analysis
repo_url: https://github.com/taranis-ai/sentiment-analysis
