name: Build Package

on:
  push:
    branches:
      - master
    tags:
      - "**"
  workflow_dispatch:
  pull_request:

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  test:
    name: pytest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/huggingface
            ~/nltk_data
          key: ${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Lint with ruff
        run: ruff check --output-format=github .

      - name: test
        run: pytest

  build_wheel:
    name: build wheel
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: build
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/taranis_sentiment_analysis-*.whl
            dist/taranis_sentiment_analysis-*.tar.gz
      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
